language: python

sudo: false
env:
  matrix:
    - DOCS="true"
    - TESTS="true"
  global:
    - secure: "KWXpNwAk9XP5YGWZ1MnIuiPZ/QLKzLQ0Njqx0nrtjuubqIF82n8Xr2eLN+N9sO7feeBU0+7EnrlNBFLrAuzy6hYMGHglUs1RjyDo2UyEKGd4vU0h5YyCnwXAL9hITPauWyUHhKcLIK7fg5tXtEebjKg3vB34zFDCIFnb1VRVTP6nh+ozAh99IcFxFzsg3rt29PwsW2JSZ6vsRJFQhZuesdG/rgVf+ZwWYR6VBNCUa29cAyOsjLnwRWAwQIehoRKa+DbC7NEXTiY8nKzXgi4CRXg6lg6p51iJYpJ6sJC7efA0X2UFltP+MWDi/9Ti1WpGHpFdiQ89QQWq36aRyvxABbaH+3fo1G5qBPBUdpojKY/Wm0iR5b8GIf3NhTiLnTVU8MyI29T7/DVaf1rxGciHQDIvvyQOE1UdR274D3xumxcHfZmnxBMq4Rhe9YLsD1hSh/1ISJwm5xTgUS9N0teTEMrcORwBRkUZVZyFbRGvK8EiJKD/Edzx3zZlS39DpYww+o05dQjlrPNfrWU1wwiNnZZYXbaz5BTKuuhnONL+wgLyalBKoeK4rUSwQsRebu7NfcwrwzAc3paW/32LdGK7l6Nc/C5xt2Doh1j0hL5w/X7K6hTgZc8erNqSljOtApU24f1U7JRWHQhLrKgaBOKqkVZ6ynFJ+pez6l2qCjiNGYs="
        

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge # For sphinxcontrib.autoprogram
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=3.5 requests cryptography sphinx pyflakes sphinxcontrib-autoprogram=0.1.2
  - source activate test-environment

script:
  - set -e
  - if [[ "${DOCS}" == "true" ]]; then
      cd docs;
      make html;
      cd ..;
      python -m doctr deploy --deploy-repo doctrtesting/doctrtesting.github.io;
    fi

  - if [[ "${TESTS}" == "true" ]]; then
      pyflakes doctr;
    fi
