language: python

sudo: false
env:
  matrix:
    - DOCS="true"
    - TESTS="true"
  global:
    - secure: "Kf/8FAb2/TrOS+QYkWYzQKTuDTpaQawM7hD6coMuAWM6PvCGfsOANGNCizk4ke1DYgYEiggZD44Qm3R5RX4immPfkw1a/m5vhe+2PoW3X7kuDZTWqp9tVp5SdZw/OpcTYSHaswdhYhkhJWZNFC7hxtMDMQqDZDfyANUQkol8W6e4ftWXKRuwNAQehhs1s9ZtejKsNHXMUqv+tADrlPraoyhRuWXhdVaJNOYlUvQxUjYO1YpJ5vdmSJXkGm83RHzhAba8/O/kOQYUzu9gEZuJR087NC9y9P4KRoNXLLikMFTpVsvNZKZIRZMCe+pO+Nr73YPH7gKruGmGn7IUVN3pcvkcdYmUb5a/pgHCNXGvNWmhBZryKuBH/k9Ugu1FEzE+J77KMRIlEiRtHyfNdyMvqoRECRNoserh8l3nOkwTLSk/19Ofmvu6ZfXmyErtYw7T2Khr7utBcIV1kQQcmMxO8KxYBZqeRo3/IZuSqBIwCJxWNiRDJ8cr3VfpJiK+i/MlLhZFe4zFlwik5uyePq3orro6uMAySCd39QnHFfASbO4eE+2FR21i1KIs0wfBDkRDju4usUBXm+jh+gshBson+SKMz0f0SgNZlcIg3On0b3QHK/3bZxuorD4AaJtiCpnwWUctH60O2O+swbt1HKQ5KxF9BudT+HyKPfRct6GJ8l4="


install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge # For sphinxcontrib.autoprogram
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=3.5 requests cryptography sphinx pyflakes sphinxcontrib-autoprogram=0.1.2
  - source activate test-environment

script:
  - set -e
  - if [[ "${DOCS}" == "true" ]]; then
      cd docs;
      make html;
      cd ..;
      python -m doctr deploy --deploy-repo gforsyth/doctrdocs
    fi

  - if [[ "${TESTS}" == "true" ]]; then
      pyflakes doctr;
    fi
